services:
  - type: web
    name: litellm-proxy
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LITELLM_MASTER_KEY
        sync: false
      - key: CUSTOM_OPENAI_API_KEY
        sync: false
      - key: CUSTOM_OPENAI_API_BASE
        sync: false
